### PR TITLE
PLCRVoting edge case

### PR DESCRIPTION
**Pull request by hodkov**
Let’s assume that PLCR(DLL + AttributeStore) for my account contains the following data `{ 1(1)-2(2) }`. This means that for voting with id=1 : 1 token has been committed, for voting with id=2 : 2 tokens have been committed, correspondingly.
Then I call  commitVote in voting with id=3 and bet 10 tokens.
To get the value of `_prevPollID` we use method `PLCRVoting.getInsertPointForNumTokens`. In our case the result will be `_prevPollID = 2`.
So, now after `commitVote`, data will be set to `{ 1(1)-2(2)-3(10) }`
But then, during the commit period, I decided to change my vote and rise my bet to 100 tokens. I call `commitVote` in voting with id=3 and bet 100 tokens.
Method `PLCRVoting.getInsertPointForNumTokens` will return `_prevPollID = 3` that why I have to call `PLCRVoting.commitVote` with the following parameters `commitVote(3, _secretHash, 100, 3)`.
In the current implementation of `PLCRVoting` и `DLL` for the current example there will be a call of `DLL.insert(3, 3, 0)` that will remove voting with id=3 and lead to exception.
As a side effect, the `PLCRVoting.hasBeenRevealed` method will return` true` for voting with id=3, despite the fact that `PLCRVoting.revealVote` was not called.
In the implementation of `DLL` from the commit https://github.com/skmgoldin/tcr/tree/b963a652b71097222087c62666e3edb1867511a1
there will also be an attempt to call `DLL.insert (3, 3, 0)` which will "corrupt" the DLL’s state and result in a vote for my account being impossible.

### CODE REVIEW

**Comment by skmgoldin** [comment]
This is partially addressed upstream in the DLL repo: https://github.com/skmgoldin/sol-dll/issues/2

But it looks like you may have found another bug in `getInsertPointForNumTokens`. We will take a look!

**Comment by kangarang** [comment]
This is great.

Tests here: https://github.com/ConsenSys/PLCRVoting/pull/31

@hodkov 's PR makes the failing test pass.

@skmgoldin , how would you like to proceed? should we have @hodkov  move this PR to the [PLCRVoting](https://github.com/ConsenSys/PLCRVoting/pulls) repo?

**Comment by skmgoldin** [comment]
Yes.

**Comment by kangarang** [comment]
Resolved using `getInsertPointForNumTokens`:

6ec8fcc6a098e8fc61b67539980fc0fe1c31f9f4

**Pull request closed without merging**
