### PR TITLE
Improve deploy pipeline

### PR DESCRIPTION
**Pull request by skmgoldin**
The deploy pipeline is somewhat brittle and requires addresses be specified uniquely for deployment to any given network. This can be abstracted such that addresses and token amounts can be specified once and network choice can be deferred to Truffle.

* Move EPM install into npm i step
* Fix bad migration numbering
* Implement new config file format. The new format includes a "token" property which is an object. If "deployToken" is false, a token at the provided address will be used in the deployment. If deployToken is true, a new token will be deployed with the specified properties and tokens will be distributed to the addresses specified in the tokenHolders array. The tokenHolders array is an array of objects with the keys "address" and "amount".
* Update README to describe new deploy process
* Update Truffle to latest

### CODE REVIEW

**Comment by kangarang** [comment]
my opinion is to remove the `install` script in `package.json`, and revert the `compile` script to: 

```json
"compile": "truffle install && truffle compile",
```

**Comment by kangarang** [comment]
interesting...

i haven't run into the same issue since the first time i experienced it.

**Comment by kangarang** [comment]
i _think_ my error was due to an issue with epm. I'm still of the opinion we should include `truffle install` in the `compile` script. Furthermore, I think we should change the install script to be named `postinstall` for clarity (https://docs.npmjs.com/misc/scripts).

```json
"postinstall": "truffle install",
"compile": "truffle install && truffle compile",
```

**Comment by skmgoldin** [comment]
> I'm still of the opinion we should include truffle install in the compile script.

I want to remove it from the compile script because `npm run compile` is probably something that people will do much more often than `npm i`, and waiting for the EPM install takes precious seconds. If you can't reproduce your issue (I can't reproduce that issue), is there a justification for putting it in the `compile` step?

**Comment by kangarang** [comment]
I was able to reproduce it once out of ~10 attempts, but i dont have any other justification since `npm i` takes seconds.

lgtm

**Comment by kangarang** [comment]
Suggestion to increase security:

Instead of relying on a mnemonic inside `secrets.json`, use an environment variable

```bash
export MNEMONIC = 'my good mnemonic'
```

```js
const HDWalletProvider = require('truffle-hdwallet-provider');

const MNEMONIC = process.env.MNEMONIC || '';

module.exports = {
  networks: {
    mainnet: {
      provider: new HDWalletProvider(MNEMONIC, 'https://mainnet.infura.io'),
      network_id: '1',
      gas: 4500000,
      gasPrice: 10000000000,
    },
    rinkeby: {
      provider: new HDWalletProvider(MNEMONIC, 'https://rinkeby.infura.io'),
      network_id: '*',
      gas: 4500000,
      gasPrice: 25000000000,
    },
    // config for solidity-coverage
    coverage: {
      host: 'localhost',
      network_id: '*',
      port: 7545, // <-- If you change this, also set the port option in .solcover.js.
      gas: 0xfffffffffff, // <-- Use this high gas value
      gasPrice: 0x01, // <-- Use this low gas price
    },
  },
};
```

**Pull request merged**
